apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uy32rws7x-python
  janus-idp.io/tekton: uy32rws7x-python
  backstage.io/kubernetes-id: uy32rws7x-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uy32rws7x-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
